#!/bin/sh
#* menuextras
#+ chris.gerke@gmail.com
#+
#+ Description: Set default Menu Extras.
#+
#+ Version: 1.0
#+
#+ History:
#+     1.0: Script.
#+
#+ TODO:
#+     * Add error checking?

ME=$0
SCRIPT_DIR="$1/Contents/Resources"
TARGET_DIR="$3"

#+ // fix
if [ -z "${TARGET_DIR}" ] || [ "${TARGET_DIR}" = "/" ]; then
 TARGET_DIR=""
fi

#+ UUID
if [[ `ioreg -rd1 -c IOPlatformExpertDevice | /usr/bin/grep -i "UUID" | cut -c27-50` == "00000000-0000-1000-8000-" ]]; then
 UUID=`ioreg -rd1 -c IOPlatformExpertDevice | /usr/bin/grep -i "UUID" | cut -c51-62 | awk {'print tolower()'}`
elif [[ `ioreg -rd1 -c IOPlatformExpertDevice | /usr/bin/grep -i "UUID" | cut -c27-50` != "00000000-0000-1000-8000-" ]]; then
 UUID=`ioreg -rd1 -c IOPlatformExpertDevice | /usr/bin/grep -i "UUID" | cut -c27-62`
fi

#+ Apple User Template, booted volume only
for USER_TEMPLATE in `sudo /bin/ls "/System/Library/User Template"`
do
 if [ -r "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences" ]; then
  sudo /bin/mkdir -p "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/ByHost"
  #+ com.apple.systemuiserver.plist
  sudo /usr/libexec/PlistBuddy -c 'Delete menuExtras' "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/com.apple.systemuiserver.plist"
  sudo /usr/libexec/PlistBuddy -c 'Add menuExtras array' "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/com.apple.systemuiserver.plist" 
  sudo /usr/libexec/PlistBuddy -c 'Add menuExtras:0 string /Applications/Utilities/Keychain\ Access.app/Contents/Resources/Keychain.menu' "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/com.apple.systemuiserver.plist"
  sudo /usr/libexec/PlistBuddy -c 'Add menuExtras:1 string /System/Library/CoreServices/Menu\ Extras/Bluetooth.menu' "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/com.apple.systemuiserver.plist"
  sudo /usr/libexec/PlistBuddy -c 'Add menuExtras:2 string /System/Library/CoreServices/Menu\ Extras/TextInput.menu' "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/com.apple.systemuiserver.plist"
  sudo /usr/libexec/PlistBuddy -c 'Add menuExtras:3 string /System/Library/CoreServices/Menu\ Extras/Volume.menu' "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/com.apple.systemuiserver.plist"
  sudo /usr/libexec/PlistBuddy -c 'Add menuExtras:4 string /System/Library/CoreServices/Menu\ Extras/Displays.menu' "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/com.apple.systemuiserver.plist"
  sudo /usr/libexec/PlistBuddy -c 'Add menuExtras:5 string /System/Library/CoreServices/Menu\ Extras/RemoteDesktop.menu' "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/com.apple.systemuiserver.plist"
  #+ com.apple.systemuiserver.${UUID}.plist
  sudo /usr/libexec/PlistBuddy -c 'Delete dontAutoLoad' "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/ByHost/com.apple.systemuiserver.${UUID}.plist"
  sudo /usr/libexec/PlistBuddy -c 'Add dontAutoLoad array' "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/ByHost/com.apple.systemuiserver.${UUID}.plist"
  sudo /usr/libexec/PlistBuddy -c 'Add dontAutoLoad:0 string /System/Library/CoreServices/Menu\ Extras/TimeMachine.menu' "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/ByHost/com.apple.systemuiserver.${UUID}.plist"
  #+ Laptop?
  ioreg -rd1 -c IOPlatformExpertDevice | grep -E model | awk '{print $3}' | sed s/\<\"// | sed s/\"\>// | grep "Book"
  if [ "$?" == "1" ]; then
   #+ com.apple.systemuiserver.${UUID}.plist for non-laptop
   sudo /usr/libexec/PlistBuddy -c 'Add dontAutoLoad:0 string /System/Library/CoreServices/Menu\ Extras/AirPort.menu' "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/ByHost/com.apple.systemuiserver.${UUID}.plist"
   sudo /usr/libexec/PlistBuddy -c 'Add dontAutoLoad:1 string /System/Library/CoreServices/Menu\ Extras/VPN.menu' "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/ByHost/com.apple.systemuiserver.${UUID}.plist"
   sudo /usr/libexec/PlistBuddy -c 'Add dontAutoLoad:2 string /System/Library/CoreServices/Menu\ Extras/Battery.menu' "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/ByHost/com.apple.systemuiserver.${UUID}.plist"
  else
   #+ com.apple.systemuiserver.plist for laptop
   sudo /usr/libexec/PlistBuddy -c 'Add menuExtras:6 string /System/Library/CoreServices/Menu\ Extras/AirPort.menu' "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/com.apple.systemuiserver.plist"
   sudo /usr/libexec/PlistBuddy -c 'Add menuExtras:7 string /System/Library/CoreServices/Menu\ Extras/VPN.menu' "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/com.apple.systemuiserver.plist"
   sudo /usr/libexec/PlistBuddy -c 'Add menuExtras:8 string /System/Library/CoreServices/Menu\ Extras/Battery.menu' "/System/Library/User Template/${USER_TEMPLATE}/Library/Preferences/com.apple.systemuiserver.plist"
  fi
 fi
done

#+ Existing users booted volume only
for USER_DIR in `sudo /bin/ls "/Users"`
do
 if [ -r "/Users/${USER_DIR}/Library/Preferences" ]; then
  sudo /bin/mkdir -p "/Users/${USER_DIR}/Library/Preferences/ByHost"
  #+ com.apple.systemuiserver.plist
  sudo /usr/libexec/PlistBuddy -c 'Delete menuExtras' "/Users/${USER_DIR}/Library/Preferences/com.apple.systemuiserver.plist"
  sudo /usr/libexec/PlistBuddy -c 'Add menuExtras array' "/Users/${USER_DIR}/Library/Preferences/com.apple.systemuiserver.plist" 
  sudo /usr/libexec/PlistBuddy -c 'Add menuExtras:0 string /Applications/Utilities/Keychain\ Access.app/Contents/Resources/Keychain.menu' "/Users/${USER_DIR}/Library/Preferences/com.apple.systemuiserver.plist"
  sudo /usr/libexec/PlistBuddy -c 'Add menuExtras:1 string /System/Library/CoreServices/Menu\ Extras/Bluetooth.menu' "/Users/${USER_DIR}/Library/Preferences/com.apple.systemuiserver.plist"
  sudo /usr/libexec/PlistBuddy -c 'Add menuExtras:2 string /System/Library/CoreServices/Menu\ Extras/TextInput.menu' "/Users/${USER_DIR}/Library/Preferences/com.apple.systemuiserver.plist"
  sudo /usr/libexec/PlistBuddy -c 'Add menuExtras:3 string /System/Library/CoreServices/Menu\ Extras/Volume.menu' "/Users/${USER_DIR}/Library/Preferences/com.apple.systemuiserver.plist"
  sudo /usr/libexec/PlistBuddy -c 'Add menuExtras:4 string /System/Library/CoreServices/Menu\ Extras/Displays.menu' "/Users/${USER_DIR}/Library/Preferences/com.apple.systemuiserver.plist"
  sudo /usr/libexec/PlistBuddy -c 'Add menuExtras:5 string /System/Library/CoreServices/Menu\ Extras/RemoteDesktop.menu' "/Users/${USER_DIR}/Library/Preferences/com.apple.systemuiserver.plist"
  #+ com.apple.systemuiserver.${UUID}.plist
  sudo /usr/libexec/PlistBuddy -c 'Delete dontAutoLoad' "/Users/${USER_DIR}/Library/Preferences/ByHost/com.apple.systemuiserver.${UUID}.plist"
  sudo /usr/libexec/PlistBuddy -c 'Add dontAutoLoad array' "/Users/${USER_DIR}/Library/Preferences/ByHost/com.apple.systemuiserver.${UUID}.plist"
  sudo /usr/libexec/PlistBuddy -c 'Add dontAutoLoad:0 string /System/Library/CoreServices/Menu\ Extras/TimeMachine.menu' "/Users/${USER_DIR}/Library/Preferences/ByHost/com.apple.systemuiserver.${UUID}.plist"
  #+ Laptop?
  ioreg -rd1 -c IOPlatformExpertDevice | grep -E model | awk '{print $3}' | sed s/\<\"// | sed s/\"\>// | grep "Book"
  if [ "$?" == "1" ]; then
   #+ com.apple.systemuiserver.${UUID}.plist for non-laptop
   sudo /usr/libexec/PlistBuddy -c 'Add dontAutoLoad:0 string /System/Library/CoreServices/Menu\ Extras/AirPort.menu' "/Users/${USER_DIR}/Library/Preferences/ByHost/com.apple.systemuiserver.${UUID}.plist"
   sudo /usr/libexec/PlistBuddy -c 'Add dontAutoLoad:1 string /System/Library/CoreServices/Menu\ Extras/VPN.menu' "/Users/${USER_DIR}/Library/Preferences/ByHost/com.apple.systemuiserver.${UUID}.plist"
   sudo /usr/libexec/PlistBuddy -c 'Add dontAutoLoad:2 string /System/Library/CoreServices/Menu\ Extras/Battery.menu' "/Users/${USER_DIR}/Library/Preferences/ByHost/com.apple.systemuiserver.${UUID}.plist"
  else
   #+ com.apple.systemuiserver.plist for laptop
   sudo /usr/libexec/PlistBuddy -c 'Add menuExtras:6 string /System/Library/CoreServices/Menu\ Extras/AirPort.menu' "/Users/${USER_DIR}/Library/Preferences/com.apple.systemuiserver.plist"
   sudo /usr/libexec/PlistBuddy -c 'Add menuExtras:7 string /System/Library/CoreServices/Menu\ Extras/VPN.menu' "/Users/${USER_DIR}/Library/Preferences/com.apple.systemuiserver.plist"
   sudo /usr/libexec/PlistBuddy -c 'Add menuExtras:8 string /System/Library/CoreServices/Menu\ Extras/Battery.menu' "/Users/${USER_DIR}/Library/Preferences/com.apple.systemuiserver.plist"
  fi
  #+ Lockfile
  sudo /bin/rm -Rf "${TARGET_DIR}/Users/${USER_DIR}/Library/Preferences/com.apple.systemuiserver.plist.lockfile"
  sudo /bin/rm -Rf "/Users/${USER_DIR}/Library/Preferences/ByHost/com.apple.systemuiserver.${UUID}.plist.lockfile"
  #+ Permissions
  sudo /usr/sbin/chown -R "${USER_DIR}" "/Users/${USER_DIR}/Library/Preferences"
 fi
done

#+ Unload Daemon
sudo /bin/rm -Rf "/Library/LaunchDaemons/MenuExtras.plist"

exit 0